apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: demo-e
  namespace: tx-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-e
  template:
    metadata:
      labels:
        app: demo-e
    spec:
      terminationGracePeriodSeconds: 60
#      hostNetwork: true
      containers:
      - name: demo-e
        image: 192.168.110.119:5000/yizhishang/demo-e
        imagePullPolicy: IfNotPresent
        # command: ["java"]
        # args: ["-jar", "/usr/local/demo-e.jar","--spring.profiles.active=test","--server.port=8300"]
        ports:
        - name: http
          containerPort: 8080
        # livenessProbe:
        #   failureThreshold: 3
        #   httpGet:
        #     path: /actuator/health
        #     port: 8080
        #     scheme: HTTP
        #   initialDelaySeconds: 20
        #   periodSeconds: 10
        #   successThreshold: 1
        #   timeoutSeconds: 1
        # readinessProbe:
        #   failureThreshold: 3
        #   httpGet:
        #     path: /actuator/health
        #     port: 8080
        #     scheme: HTTP
        #   initialDelaySeconds: 20
        #   periodSeconds: 10
        #   successThreshold: 1
        #   timeoutSeconds: 1
---

apiVersion: v1
kind: Service
metadata:
  name: demo-e
  namespace: tx-manager
  labels:
    app: demo-e
spec:
  selector:
    app: demo-e
  clusterIP: None
  ports:
    - name: http
      port: 8080
      protocol: TCP