version: '3.3'
services:

#  redis:
#    image: redis:5.0.3-alpine
#    ports:
#      - 6379:6379
#    command: redis-server --save "" --maxmemory 200Mb --timeout 0 --tcp-keepalive 60 --bind 0.0.0.0
#    deploy:
#      restart_policy:
#        condition: on-failure
#        delay: 10s
#        max_attempts: 3
#        window: 120s
#      placement:
#        constraints: [node.role == manager]

  eureka-server:
    image: 192.168.110.117:5000/yizhishang/eureka-server:latest
    ports:
      - 1111:1111
    environment:
      server.port: 1111
    networks:
      - net
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s
      placement:
        constraints: [node.role == manager]

  tx-manager:
    image: 192.168.110.117:5000/yizhishang/tx-manager:latest
    ports:
      - 7970:7970
#      - 8070:8070
      - 7971:7971
    networks:
      - net
    environment:
      server.port: 7970
#      tx-lcn.manager.host: 192.168.110.117
      tx-lcn.manager.port: 7971
      tx-lcn.manager.adminKey: root
      spring.redis.host: 192.168.110.117
      spring.redis.port: 6379
      spring.datasource.driver-class-name: com.mysql.jdbc.Driver
      spring.datasource.url: jdbc:mysql://192.168.110.1:3306/tx-manager?characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
      spring.datasource.username: root
      spring.datasource.password: root
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s
      placement:
        constraints: [node.role == manager]

  spring-demo-client:
    image: 192.168.110.117:5000/yizhishang/spring-demo-client:latest
    ports:
      - 8081:8081
    depends_on:
      - tx-manager
      - eureka-server
    networks:
      - net
    environment:
      server.port: 8081
      spring.redis.host: 192.168.110.117
      spring.redis.port: 6379
      eureka.client.service-url.defaultZone: http://eureka-server:1111/eureka
      spring.datasource.driver-class-name: com.mysql.cj.jdbc.Driver
      spring.datasource.url: jdbc:mysql://192.168.110.1:3306/txlcn-demo?characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
      spring.datasource.username: root
      spring.datasource.password: root
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s

#  spring-demo-d:
#    image: 192.168.110.117:5000/yizhishang/spring-demo-d:latest
#    ports:
#      - 8082:8082
#    depends_on:
#      - eureka-server
#      - tx-manager
#    environment:
#      server.port: 8082
#      spring.redis.host: 192.168.110.117
#      spring.redis.port: 6379
#      eureka.client.service-url.defaultZone: http://eureka-server:1111/eureka
#      spring.datasource.driver-class-name: com.mysql.cj.jdbc.Driver
#      spring.datasource.url: jdbc:mysql://192.168.110.1:3306/txlcn-demod?characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
#      spring.datasource.username: root
#      spring.datasource.password: root
#    deploy:
#      mode: replicated
#      replicas: 2
#      restart_policy:
#        condition: on-failure
#        delay: 10s
#        max_attempts: 3
#        window: 120s
#
#  spring-demo-e:
#    image: 192.168.110.117:5000/yizhishang/spring-demo-e:latest
#    ports:
#      - 8083:8083
#    depends_on:
#      - eureka-server
#      - tx-manager
#    deploy:
#      mode: replicated
#      replicas: 2
#      restart_policy:
#        condition: on-failure
#        delay: 10s
#        max_attempts: 3
#        window: 120s
#    environment:
#      server.port: 8083
#      spring.redis.host: 192.168.110.117
#      spring.redis.port: 6379
#      eureka.client.service-url.defaultZone: http://eureka-server:1111/eureka
#      spring.datasource.driver-class-name: com.mysql.cj.jdbc.Driver
#      spring.datasource.url: jdbc:mysql://192.168.110.1:3306/txlcn-demoe?characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
#      spring.datasource.username: root
#      spring.datasource.password: root

networks:
  net: