version: '3'
services:

  eureka-server:
    container_name: eureka-server
    image: 192.168.110.117:5000/yizhishang/eureka-server:latest
    restart: on-failure:10
    ports:
      - 192.168.110.117:1111:1111
    environment:
      server.port: 1111

  tx-manager:
    container_name: tx-manager
    image: 192.168.110.117:5000/yizhishang/tx-manager:latest
    restart: always
    ports:
      - 192.168.110.117:7970:7970
      - 8070:8070
    environment:
      server.port: 7970
      tx-lcn.manager.adminKey: root
      spring.redis.host: 192.168.110.117
      spring.redis.port: 6379
      spring.datasource.driver-class-name: com.mysql.jdbc.Driver
      spring.datasource.url: jdbc:mysql://192.168.110.1:3306/tx-manager?characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
      spring.datasource.username: root
      spring.datasource.password: root

  spring-demo-client:
    container_name: spring-demo-client
    image: 192.168.110.117:5000/yizhishang/spring-demo-client:latest
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - tx-manager
      - eureka-server
    environment:
      server.port: 8081
      spring.redis.host: 192.168.110.117
      spring.redis.port: 6379
      eureka.client.service-url.defaultZone: http://eureka-server:1111/eureka
      spring.datasource.driver-class-name: com.mysql.cj.jdbc.Driver
      spring.datasource.url: jdbc:mysql://192.168.110.1:3306/txlcn-demo?characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
      spring.datasource.username: root
      spring.datasource.password: root

  spring-demo-d:
    container_name: spring-demo-d
    image: 192.168.110.117:5000/yizhishang/spring-demo-d:latest
    restart: always
    ports:
      - 8082:8082
    depends_on:
      - eureka-server
      - tx-manager
    environment:
      server.port: 8082
      spring.redis.host: 192.168.110.117
      spring.redis.port: 6379
      eureka.client.service-url.defaultZone: http://eureka-server:1111/eureka
      spring.datasource.driver-class-name: com.mysql.cj.jdbc.Driver
      spring.datasource.url: jdbc:mysql://192.168.110.1:3306/txlcn-demod?characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
      spring.datasource.username: root
      spring.datasource.password: root

  spring-demo-e:
    container_name: spring-demo-e
    image: 192.168.110.117:5000/yizhishang/spring-demo-e:latest
    restart: always
    ports:
      - 8083:8083
    depends_on:
      - eureka-server
      - tx-manager
    environment:
      server.port: 8083
      spring.redis.host: 192.168.110.117
      spring.redis.port: 6379
      eureka.client.service-url.defaultZone: http://eureka-server:1111/eureka
      spring.datasource.driver-class-name: com.mysql.cj.jdbc.Driver
      spring.datasource.url: jdbc:mysql://192.168.110.1:3306/txlcn-demoe?characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
      spring.datasource.username: root
      spring.datasource.password: root