version: '3.3'
services:

  spring-demo-client:
    image: 192.168.110.117:5000/yizhishang/spring-demo-client:latest
    ports:
      - 8081:8081
    depends_on:
      - tx-manager
      - eureka-server
    networks:
      - net
    environment:
      spring.profiles.active: dev
      server.port: 8081
      eureka.client.service-url.defaultZone: http://eureka-server:1111/eureka
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s

  spring-demo-d:
    image: 192.168.110.117:5000/yizhishang/spring-demo-d:latest
    depends_on:
      - eureka-server
      - tx-manager
    networks:
      - net
    environment:
      server.port: 8082
      spring.profiles.active: dev
      eureka.client.service-url.defaultZone: http://eureka-server:1111/eureka
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s

  spring-demo-e:
    image: 192.168.110.117:5000/yizhishang/spring-demo-e:latest
    depends_on:
      - eureka-server
      - tx-manager
    networks:
      - net
    deploy:
      mode: replicated
      replicas: 2
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s
    environment:
      server.port: 8083
      spring.profiles.active: dev
      eureka.client.service-url.defaultZone: http://eureka-server:1111/eureka

networks:
  net:
    driver: overlay