eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
spring:
  application:
    name: eureka-server


opentracing:
  jaeger:
    udp-sender:
      host: 192.168.110.119
      port: 32030
    log-spans: true
  spring:
    cloud:
      async:
        enabled: true
server:
  port: 8888